name: Docker build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ECR_REGISTRY_NAME: 1056-repository
  ECR_REGISTRY_URL: 244530008913.dkr.ecr.eu-west-1.amazonaws.com

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |  
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY_URL }}
          rev=$(git rev-parse --short HEAD)
          docker build . -t shopify
          docker tag shopify ${{ env.ECR_REGISTRY_URL }}/${{ env.ECR_REGISTRY_NAME }}:$rev
          if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$GITHUB_REF" == "refs/heads/main" ]
          then
            docker tag shopify ${{ env.ECR_REGISTRY_URL }}/${{ env.ECR_REGISTRY_NAME }}:latest
          fi
          docker push --all-tags ${{ env.ECR_REGISTRY_URL }}/${{ env.ECR_REGISTRY_NAME }}